config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "login" , to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, only: %i(new create edit update)
  resources :microposts, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<hr>
<nav class="navbar navbar-buttom" role="navigation">
  <div class="container">
    <small><%= t("footer.small_content", first_link: link_to(t(".first_href"), "http://www.railstutorial.org"),
      second_link: link_to(t(".second_href"), "http://www.michaelhartl.com")).html_safe %>
    </small>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><%= link_to t("static_pages.about.title_about"), static_pages_about_path %></li>
      <li><%= link_to t("static_pages.contact.contact_title"), static_pages_contact_path %></li>
      <li><%= link_to t("static_pages.new.title_new"), new_user_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_header.html.erb
<div class="container header">
  <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
      <%= link_to t("title_header"), root_path, class: "navbar-brand" %>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to t("static_pages.home.title_home"), root_path %></li>
        <li><%= link_to t("static_pages.help.title_help"), static_pages_help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("users.title_user"), users_path %></li>
          <li class="dropdown">
            <%= link_to t("users.dropmenu.account"), "#", class: "dropdown-toggle", data: {toggle: "dropdown"} %>
            <ul class="dropdown-menu">
              <li><%= link_to t("users.dropmenu.profile"), user_path(current_user) %></li>
              <li><%= link_to t("users.dropmenu.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("users.dropmenu.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("login"), login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/header" %>
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= render "layouts/footer.html.erb" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>